import type { Metadata } from "next";
import "./globals.scss";
import AuthProvider from "./components/AuthProvider/AuthProvider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Open Demat account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://hv-camera-web-sg.s3-ap-southeast-1.amazonaws.com/hyperverge-web-sdk@9.3.1/src/sdk.min.js"
          strategy="beforeInteractive" // Load before hydration
        />
      </head>
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
